android.useAndroidX=true
ANDROID_COMPILE_SDK=35
ANDROID_TARGET_SDK=35
ANDROID_MIN_SDK=28
ANDROID_NDK_VERSION=27.3.13750724
PROJECT_ARTIFACT_GROUP=com.vnova.lcevc.decoder
PROJECT_ARTIFACT_NAME=dec
PROJECT_RELEASE_NAME=LCEVCdec
PROJECT_RELEASE_DESCRIPTION=Java Native Interface wrapper of the LCEVCdec project
PROJECT_LICENSE_NAME=BSD-3-Clause-Clear License
PROJECT_LICENSE_URL=https://github.com/v-novaltd/LCEVCdec/blob/main/LICENSE.md
