[versions]
agp = "8.13.2"
gmsStrictVersionMatcher = "1.2.4"
junit = "4.12"
kotlin = "2.3.0"
mockitoInline = "3.12.4"

[libraries]
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
gms-strict-version-matcher = { module = "com.google.android.gms:strict-version-matcher-plugin", version.ref = "gmsStrictVersionMatcher" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockitoInline" }
